### ISSUE TITLE
Can't checkout on Windows

### ISSUE THREAD

**Issue by patricknelson** [Holben888/eleventy-vite-jam-sandwich#1]
Just a super minor request. 😅 I wanted to clone this down to check this out on Windows but hit a roadblock on literally `git` checking it out due to the colons in the filenames in the assets directory (yes, don't be fooled, I'm using `bash`, but it's Cygwin still running on native Windows):

```
$ git restore --source=head :/
error: invalid path 'assets/images/Jamstack:-how-it-started-how-it's-going.webp'
error: invalid path 'assets/images/Twilio-Console:-A-Large-Scale-Migration-to-Jamstack.webp'
```

**Comment by ghost** [comment]
Merged, thanks for fixing!
